# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.0 on Sun Aug 16 14:56:05 2015
#

import wx
#import wx.stc as stc
import wx.richtext as richtext
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ThagWorldFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.world = kwds['world']
        kwds.pop('world')
        # begin wxGlade: ThagWorldFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.thag_world_frame_menubar = wx.MenuBar()
        self.SetMenuBar(self.thag_world_frame_menubar)
        # Menu Bar end
        self.text_output = richtext.RichTextCtrl(self, wx.ID_ANY)
        self.output = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.button_1 = wx.Button(self, wx.ID_ANY, "Send")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.OnSend, self.output)
        self.Bind(wx.EVT_BUTTON, self.OnSend, self.button_1)
        # end wxGlade

        #self.text_output.SetUseHorizontalScrollBar(0)
        #self.text_output.SetWrapMode(stc.STC_WRAP_WORD)

        self.telnet = None

    def __set_properties(self):
        # begin wxGlade: ThagWorldFrame.__set_properties
        self.SetTitle("frame_3")
        # end wxGlade
        self.SetTitle(self.world.name)

    def __do_layout(self):
        # begin wxGlade: ThagWorldFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.text_output, 5, wx.EXPAND, 0)
        sizer_3.Add(self.output, 8, wx.EXPAND, 0)
        sizer_3.Add(self.button_1, 1, 0, 0)
        sizer_2.Add(sizer_3, 1, wx.ALIGN_BOTTOM | wx.EXPAND | wx.FIXED_MINSIZE | wx.TOP, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        sizer_2.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def writeLine(self, line):
        self.text_output.AppendText(line)
        self.text_output.AppendText("\n")

        #self.text_output.ScrollToLine(self.text_output(GetLineCount()))
        self.text_output.ShowPosition(self.text_output.LastPosition)

    def OnSend(self, event):  # wxGlade: ThagWorldFrame.<event_handler>
        tts = self.output.GetLineText(0)

        ## Let the world handle the text output.
        self.world.send(tts)
        self.output.Clear()

# end of class ThagWorldFrame
